name: Build Sakr Menu
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/sdks/master/install.sh)"
      - name: Build Dylib
        run: make package
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: Sakr-Dylib
          path: packages/*.deb
